name: Generate metrics

on:
  schedule:
    - cron: "19 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Tapawingo
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.svg
          template: terminal
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
